export const ROUTES = {
  PAY: "/test/pay",
  SUBSCRIBE: "/test/subscribe",
  READER_START_REG: "/reader/start-process-register",
  READER_ACTIVATION: "/reader/activateAccount",
  //READER_REG_FORM: "/reader/get-form-fields",
  //READER_REGISTER: "/reader/register",
  GENRES: "/genre",
  TASK_FORM_FIELDS: "/task/get-form-fields",
  TASK_SUBMIT_FORM: "/task/submit-form",
  AUTH_LOGIN: "/auth/login",
  MERCHANT_REGISTER: "/merchant",
  MERCHANT_ALL_ACTIVE: "/merchant/active",
  WRITER_START_REG: "/writer/start-process-register",
  WRITER_ACTIVATION: "/writer/activateAccount",
  ORDER: "/order",
};
