export const ROUTES = {
  PAY: "/test/pay",
  SUBSCRIBE: "/test/subscribe",
  READER_START_REG: "/reader/start-process-register",
  READER_ACTIVATION: "/reader/activateAccount",
  GENRES: "/genre",
  TASK_FORM_FIELDS: "/task/get-form-fields",
  TASK_SUBMIT_FORM: "/task/submit-form",
  AUTH_LOGIN: "/auth/login",
  MERCHANT_REGISTER: "/merchant",
  MERCHANT_ALL_ACTIVE: "/merchant/active",
  ORDER: "/order",
  WRITER_START_REG: "/writer/start-process-register",
  WRITER_ACTIVATION: "/writer/activateAccount",
  WRITER_GET_TASK_ID: "/writer/getTaskId",
  LITERARY_WORK_UPLOAD: "/literaryWork/upload",
  BOOK_REQUEST_START_PUBLISHING: "/bookRequest/start-process-book-publishing",
};
